---
- name: Create directory /etc/rancher/k3s
  ansible.builtin.file:
    path: /etc/{{ item }}
    state: directory
    mode: "0755"
  loop:
    - rancher
    - rancher/k3s

- name: Insert registries into /etc/rancher/k3s/registries.yaml
  ansible.builtin.blockinfile:
    path: /etc/rancher/k3s/registries.yaml
    block: "{{ custom_registries_yaml }}"
    mode: "0600"
    create: true
