---
- name: Enable cgroup via boot commandline if not already enabled
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  when:
    - ansible_distribution == 'Ubuntu'

- name: Reboot to enable cgroups
  reboot:
  when:
    - ansible_distribution == 'Ubuntu'
