---
- name: Create k3s.service.d directory
  ansible.builtin.file:
    path: "{{ systemd_dir }}/k3s.service.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy K3s http_proxy conf file
  ansible.builtin.template:
    src: http_proxy.conf.j2
    dest: "{{ systemd_dir }}/k3s.service.d/http_proxy.conf"
    owner: root
    group: root
    mode: "0755"
